//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investment
    {
        public int InvestID { get; set; }
        public int InvestAmount { get; set; }
        public int InterestRate { get; set; }
        public decimal NumOfYears { get; set; }
        public string InterestType { get; set; }
        public string InvestType { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Interest_Type Interest_Type { get; set; }
        public virtual Investment_Type Investment_Type { get; set; }
    }
}
