//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INF272ProjectEntities1 : DbContext
    {
        public INF272ProjectEntities1()
            : base("name=INF272ProjectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Budget_Limit> Budget_Limits { get; set; }
        public virtual DbSet<Budget_Limit_Type> Budget_Limit_Types { get; set; }
        public virtual DbSet<Compound_Interest> Compound_Interests { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_Networth> Customer_Networths { get; set; }
        public virtual DbSet<Fixed_Interest> Fixed_Interests { get; set; }
        public virtual DbSet<Income> Incomes { get; set; }
        public virtual DbSet<Income_Type> Income_Types { get; set; }
        public virtual DbSet<Interest_Type> Interest_Types { get; set; }
        public virtual DbSet<Investment_Type> Investment_Types { get; set; }
        public virtual DbSet<Investments_Made> Investments_Mades { get; set; }
        public virtual DbSet<Spending_Transaction> Spending_Transactions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
