//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetToSave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationLocation
    {
        public int DonationLocation1 { get; set; }
        public int LocationID { get; set; }
        public int DonationID { get; set; }
    
        public virtual Donation Donation { get; set; }
        public virtual Location Location { get; set; }
    }
}
