//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetToSave.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserID { get; set; }
        [Required(ErrorMessage = "Required")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Required")]
        public string UserSurname { get; set; }
        [Required(ErrorMessage = "Required")]
        public string UserUseName { get; set; }
        [Required(ErrorMessage = "Required")]
        public string UserPassword { get; set; }
        [Required(ErrorMessage = "Required")]
        public int UserTypeID { get; set; }
        public Nullable<int> BudgetLimitID { get; set; }
        public Nullable<int> MonthlySpendingID { get; set; }
        public Nullable<int> NetWorthID { get; set; }
        public Nullable<int> IncomeID { get; set; }
        public Nullable<int> InvestmentID { get; set; }
        public Nullable<int> DonationID { get; set; }
    
        public virtual BudgetLimit BudgetLimit { get; set; }
        public virtual Donation Donation { get; set; }
        public virtual Income Income { get; set; }
        public virtual Investment Investment { get; set; }
        public virtual MonthlySpending MonthlySpending { get; set; }
        public virtual NetWorth NetWorth { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
